# Puerto donde correrá el microservicio
server.port=3004

# Configuración de la base de datos PostgreSQL (ajusta estos valores)
spring.datasource.url=jdbc:postgresql://44.219.96.83:5432/register_db
spring.datasource.username=register_user
spring.datasource.password=...

# Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA (Hibernate)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Tiempo máximo de espera para conexiones
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=5
